repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements
      - id: forbid-submodules
      - id: check-toml
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: local
    hooks:
      - id: nox
        name: nox
        entry: uv
        args: ["run", "nox", "-s", "lint", "autoformat", "typecheck", "--"]
        language: system
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]