[tool.poetry]
name = "example-project"
version = "0.1.0"
description = ""
authors = ["Rodrigo Carranza (sykire)"]
license = ""

packages = []

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
